SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT=0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `userbot_bind` (
  `id_user` int(11) NOT NULL DEFAULT 0,
  `code` varchar(8) NOT NULL DEFAULT '',
  `id_chat` int(11) NOT NULL DEFAULT 0,
  `id_duty` int(11) NOT NULL DEFAULT 0,
  `title` text NOT NULL DEFAULT '',
  PRIMARY KEY (`id_user`,`code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

--
-- Структура таблиці `userbot_data`
--

CREATE TABLE IF NOT EXISTS `userbot_data` (
  `id_user` int(11) NOT NULL DEFAULT 0,
  `token` text NOT NULL DEFAULT '',
  `btoken` text NOT NULL DEFAULT '',
  `ctoken` text NOT NULL DEFAULT '',
  `mtoken` text NOT NULL DEFAULT '',
  `bptime` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `secret` varchar(100) NOT NULL DEFAULT '',
  `access` text NOT NULL DEFAULT '',
  PRIMARY KEY (`id_user`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
